// EDIT THIS FILE to update your map. No rebuild is needed.
// Full examples and upload instructions are in EDITING-GUIDE.md.
// Stories support multiple lines between backticks. Photos go in photos/.
window.TRAVEL_CONTENT = {
  countries: [
    { name: "Kazakhstan", status: "home" },
    { name: "United States", status: "lived" },
    { name: "United Kingdom", status: "lived" },
    { name: "Albania", status: "visited" },
    { name: "Austria", status: "visited" },
    { name: "Belgium", status: "visited" },
    { name: "Czech Republic", status: "visited" },
    { name: "France", status: "visited" },
    { name: "Germany", status: "visited" },
    { name: "Hong Kong", status: "visited" },
    { name: "Iceland", status: "visited" },
    { name: "Italy", status: "visited" },
    { name: "Netherlands", status: "visited" },
    { name: "Slovenia", status: "visited" },
    { name: "Spain", status: "visited" },
    { name: "Portugal", status: "visited" },
    { name: "Turkey", status: "visited" },
    { name: "United Arab Emirates", status: "visited" },
  ],

  cities: [
    {
      id: "astana",
      name: "Astana",
      country: "Kazakhstan",
      lat: 51.1694,
      lon: 71.4304,
      heart: true,
      story: ``,
      photos: [],
    },
    {
      id: "almaty",
      name: "Almaty",
      country: "Kazakhstan",
      lat: 43.2389,
      lon: 76.886,
      story: ``,
      photos: [],
    },
    {
      id: "hong_kong",
      name: "Hong Kong",
      country: "Hong Kong",
      lat: 22.3193,
      lon: 114.1694,
      story: ``,
      photos: [
        {
          src: "photos/hong_kong/me_with_view.jpg",
          alt: "Me with on the way down from Victoria Peak",
          caption: "Victoria peak has a nice view of Hong Kong!"
        },
        {
          src: "photos/hong_kong/fun_man.jpg",
          alt: "a monastery on Lantau island"
        },
        {
          src:  "photos/hong_kong/friends_roller_coaster.jpg",
          alt: "my friends and I at Ocean Park's scariest roller coaster!",
          caption: "my friends and I at Ocean Park's scariest roller coaster!"
        }
      ],
    },
    {
      id: "london",
      name: "London",
      country: "United Kingdom",
      lat: 51.5072,
      lon: -0.1276,
      story: ``,
      photos: [],
    },
    {
      id: "oxford",
      name: "Oxford",
      country: "United Kingdom",
      lat: 51.752,
      lon: -1.2577,
      story: ``,
      photos: [],
    },
    {
      id: "edinburgh",
      name: "Edinburgh",
      country: "United Kingdom",
      lat: 55.9533,
      lon: -3.1883,
      story: ``,
      photos: [],
    },
    {
      id: "vienna",
      name: "Vienna",
      country: "Austria",
      lat: 48.2082,
      lon: 16.3738,
      story: ``,
      photos: [],
    },
    {
      id: "anchorage",
      name: "Anchorage",
      country: "United States",
      state: "Alaska",
      lat: 61.2181,
      lon: -149.9003,
      story: ``,
      photos: [],
    },
    {
      id: "new_york",
      name: "New York",
      country: "United States",
      state: "New York",
      lat: 40.7128,
      lon: -74.006,
      story: ``,
      photos: [],
    },
    {
      id: "los_angeles",
      name: "Los Angeles",
      country: "United States",
      state: "California",
      lat: 34.0522,
      lon: -118.2437,
      story: ``,
      photos: [],
    },
    {
      id: "miami",
      name: "Miami",
      country: "United States",
      state: "Florida",
      lat: 25.7617,
      lon: -80.1918,
      story: ``,
      photos: [],
    },
    {
      id: "boston",
      name: "Boston",
      country: "United States",
      state: "Massachusetts",
      lat: 42.3601,
      lon: -71.0589,
      story: ``,
      photos: [],
    },
  ],

  // States visited without a city entry can be listed here.
  // Adding a US city also marks its state as visited.
  visitedStates: ["Massachusetts","Alaska","California","Florida","New Hampshire","New York","New Jersey","Louisiana"],
};
